server:
  port: 8086
  servlet:
    context-path: /admin


spring:
  application:
    name: admin-server
  boot:
    admin:
      # Enabling Spring Boot Admin Server
      adminServer:
        enabled: true
      client:
        # You can leave this empty if the server isn't acting as a client
        url: http://admin-server:8086
      context-path: /admin 

  cloud:
    config:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: always

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka-server:8080/eureka/eureka/



zuul:
  ribbon:
    eager-load:
      enabled: true


#Setting logging levels
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.sac: DEBUG
