apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: springboot-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/proxy-pass-headers: "X-Forwarded-Prefix"
spec:
  ingressClassName: nginx
  rules:
  - host: springboot.local
    http:
      paths:
      - path: /admin(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: admin-server
            port: 
              number: 8086
