apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: springboot-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /  # Strip /admin prefix
spec:
  ingressClassName: nginx
  rules:
  - host: ""
    http:
      paths:
      - path: /admin
        pathType: Prefix
        backend:
          service:
            name: admin-server  # Must match Service name
            port: 
              number: 8086     # Must match Service port (not NodePort)
