apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: springboot-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    # NO global rewrite-target annotation to avoid breaking /admin UI
spec:
  ingressClassName: nginx
  rules:
  - host: springboot.local
    http:
      paths:
      - pathType: Prefix
        path: /eureka(/|$)(.*)
        backend:
          service:
            name: eureka-server
            port:
              number: 8080

      - pathType: Prefix
        path: /admin(/|$)(.*)
        backend:
          service:
            name: admin-server
            port:
              number: 8086

      - pathType: Prefix
        path: /(.*)
        backend:
          service:
            name: zuul-gateway
            port:
              number: 8083
