apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: confluentinc/cp-kafka:7.5.0
        ports:
        - containerPort: 9092
        env:
        # Critical configuration
        - name: KAFKA_CFG_PROCESS_ROLES
          value: ""  # Disables KRaft mode
        - name: KAFKA_CFG_NODE_ID
          value: ""
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper:2181
        # Standard configuration
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://kafka:9092
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: PLAINTEXT:PLAINTEXT
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: PLAINTEXT
        # Resource settings
        - name: KAFKA_HEAP_OPTS
          value: "-Xmx1G -Xms1G"
        # Debug logging
        - name: KAFKA_LOG4J_ROOT_LOGLEVEL
          value: "DEBUG"

---
apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  selector:
    app: kafka
  ports:
    - name: client
      port: 9092
      targetPort: 9092
      # If you need external access, uncomment:
      # nodePort: 30092
  # For internal cluster-only access:
  type: ClusterIP
  # For external access:
  # type: NodePort
